"""Render durable .repo-memory artifacts from the LLM's episode analyses.

This is the second deterministic half of the engine. It reads the work manifest
(from ``plan``) and the per-episode analyses (from the ``/repo-history`` skill),
then writes human-readable Markdown plus JSON mirrors structured for an MCP
server. Hotspots come straight from the mechanical analysis and need no LLM, so
``HOTSPOTS.md`` is always produced even if no analyses exist yet.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from . import __version__
from .models import EpisodeAnalysis, Synthesis
from .work import WORK_DIRNAME


class BuildError(RuntimeError):
    """Raised when the inputs needed to build artifacts are missing."""


@dataclass
class BuildResult:
    out_dir: Path
    files: list[str] = field(default_factory=list)
    episodes: int = 0
    decisions: int = 0
    landmines: int = 0


def build_artifacts(out_dir: Path) -> BuildResult:
    """Render all artifacts into ``out_dir`` from its ``.work`` manifest."""
    work_dir = out_dir / WORK_DIRNAME
    manifest_path = work_dir / "manifest.json"
    if not manifest_path.exists():
        raise BuildError(
            f"no manifest at {manifest_path}; run `repo-history plan` first"
        )
    manifest = json.loads(manifest_path.read_text())
    analysis = _read_json(work_dir / "analysis.json", default={})
    analyses = _load_analyses(work_dir, manifest)
    synthesis = _load_synthesis(work_dir)

    result = BuildResult(out_dir=out_dir)
    _write(out_dir, "TIMELINE.md", _render_timeline(manifest, analyses), result)
    _write(out_dir, "DECISIONS.md", _render_decisions(analyses), result)
    _write(out_dir, "LANDMINES.md", _render_landmines(analyses), result)
    _write(out_dir, "ARCHITECTURE.md", _render_architecture(analyses, synthesis), result)
    _write(out_dir, "HOTSPOTS.md", _render_hotspots(analysis), result)

    # JSON mirrors, structured for an MCP server to serve later.
    _write(out_dir, "timeline.json", _timeline_json(manifest, analyses), result)
    _write(out_dir, "decisions.json", _decisions_json(analyses), result)
    _write(out_dir, "landmines.json", _landmines_json(analyses), result)
    _write(out_dir, "hotspots.json", json.dumps(analysis.get("sections", {}).get("hotspots", []), indent=2), result)

    result.episodes = len(analyses)
    result.decisions = sum(len(a.decisions) for a in analyses)
    result.landmines = sum(len(a.landmines) for a in analyses)
    _write(out_dir, "index.json", _index_json(manifest, result), result)
    return result


# -- loading ---------------------------------------------------------------


def _read_json(path: Path, default):  # noqa: ANN001
    if not path.exists():
        return default
    return json.loads(path.read_text())


def _load_analyses(work_dir: Path, manifest: dict) -> list[EpisodeAnalysis]:
    """Load per-episode analyses, ordered to match the manifest."""
    analyses_dir = work_dir / "analyses"
    if not analyses_dir.is_dir():
        return []
    by_id: dict[str, EpisodeAnalysis] = {}
    for path in analyses_dir.glob("*.json"):
        analysis = EpisodeAnalysis.model_validate_json(path.read_text())
        by_id[analysis.id] = analysis
    order = [e["id"] for e in manifest.get("episodes", [])]
    ordered = [by_id[i] for i in order if i in by_id]
    # include any analyses not referenced by the manifest, in filename order
    ordered += [a for i, a in sorted(by_id.items()) if i not in set(order)]
    return ordered


def _load_synthesis(work_dir: Path) -> Synthesis | None:
    path = work_dir / "synthesis.json"
    if not path.exists():
        return None
    return Synthesis.model_validate_json(path.read_text())


# -- markdown rendering ----------------------------------------------------


def _provenance(manifest: dict) -> str:
    head = str(manifest.get("head", ""))[:8]
    return (
        f"> Generated by repo-history {__version__} · method `{manifest.get('method')}` "
        f"· ref `{manifest.get('ref')}` @ `{head}`"
    )


def _short(shas: list[str]) -> str:
    return ", ".join(s[:8] for s in shas)


def _render_timeline(manifest: dict, analyses: list[EpisodeAnalysis]) -> str:
    lines = ["# Timeline", "", _provenance(manifest), ""]
    if not analyses:
        lines += ["_No episode analyses yet. Run the /repo-history skill, then build._", ""]
        return "\n".join(lines)
    by_id = {a.id: a for a in analyses}
    for entry in manifest.get("episodes", []):
        analysis = by_id.get(entry["id"])
        if analysis is None:
            continue
        badge = "⏪ " if analysis.kind == "revert" else ""
        lines.append(f"## {badge}{analysis.title}")
        lines.append("")
        lines.append(analysis.summary.strip() or "_(no summary)_")
        if analysis.architecture_note:
            lines += ["", f"**Architecture:** {analysis.architecture_note.strip()}"]
        lines += ["", f"_commits: {_short(entry.get('commit_shas', []))}_", ""]
    return "\n".join(lines)


def _render_decisions(analyses: list[EpisodeAnalysis]) -> str:
    lines = ["# Decisions", ""]
    decisions = [(a, d) for a in analyses for d in a.decisions]
    if not decisions:
        return "\n".join(lines + ["_No decisions inferred yet._", ""])
    for analysis, decision in decisions:
        lines.append(f"## {decision.statement.strip()}")
        if decision.why.strip():
            lines += ["", decision.why.strip()]
        evidence = decision.evidence or [analysis.id]
        lines += ["", f"_evidence: {_short(evidence)}_", ""]
    return "\n".join(lines)


def _render_landmines(analyses: list[EpisodeAnalysis]) -> str:
    lines = [
        "# Landmines",
        "",
        "Do-not-repeat lessons: approaches that were reverted, abandoned, or removed.",
        "",
    ]
    landmines = [(a, m) for a in analyses for m in a.landmines]
    if not landmines:
        return "\n".join(lines + ["_None detected._", ""])
    for analysis, mine in landmines:
        lines.append(f"## {mine.lesson.strip()}")
        if mine.detail.strip():
            lines += ["", mine.detail.strip()]
        evidence = mine.evidence or [analysis.id]
        lines += ["", f"_evidence: {_short(evidence)}_", ""]
    return "\n".join(lines)


def _render_architecture(
    analyses: list[EpisodeAnalysis], synthesis: Synthesis | None
) -> str:
    lines = ["# Architecture", ""]
    if synthesis and synthesis.architecture_overview.strip():
        lines += [synthesis.architecture_overview.strip(), ""]
    else:
        lines += ["_Run the reduce step of the /repo-history skill for an overview._", ""]
    notes = [(a.title, a.architecture_note) for a in analyses if a.architecture_note]
    if notes:
        lines += ["## How it evolved", ""]
        for title, note in notes:
            lines.append(f"- **{title}**: {note.strip()}")
        lines.append("")
    return "\n".join(lines)


def _render_hotspots(analysis: dict) -> str:
    sections = analysis.get("sections", {})
    hotspots = sections.get("hotspots", [])[:25]
    coupling = sections.get("coupling", [])[:20]
    lines = ["# Hotspots", "", "Mechanically mined; no LLM involved.", ""]
    if hotspots:
        lines += ["## Most-changed files", "", "| file | commits | churn |", "| --- | ---: | ---: |"]
        for h in hotspots:
            lines.append(f"| `{h['path']}` | {h['commits']} | {h['churn']} |")
        lines.append("")
    if coupling:
        lines += [
            "## Change coupling",
            "",
            "Files that repeatedly change together.",
            "",
            "| file A | file B | co-changes | confidence |",
            "| --- | --- | ---: | ---: |",
        ]
        for c in coupling:
            lines.append(
                f"| `{c['a']}` | `{c['b']}` | {c['co_changes']} | {c['confidence']} |"
            )
        lines.append("")
    if not hotspots and not coupling:
        lines += ["_No mechanical signal available._", ""]
    return "\n".join(lines)


# -- json mirrors ----------------------------------------------------------


def _timeline_json(manifest: dict, analyses: list[EpisodeAnalysis]) -> str:
    by_id = {a.id: a for a in analyses}
    items = []
    for entry in manifest.get("episodes", []):
        analysis = by_id.get(entry["id"])
        if analysis is None:
            continue
        items.append(
            {
                "id": analysis.id,
                "title": analysis.title,
                "kind": analysis.kind,
                "summary": analysis.summary,
                "architecture_note": analysis.architecture_note,
                "commit_shas": entry.get("commit_shas", []),
                # paths let the MCP server answer "why is *this file* like this?"
                "paths": entry.get("paths", []),
            }
        )
    return json.dumps(items, indent=2)


def _decisions_json(analyses: list[EpisodeAnalysis]) -> str:
    items = [
        {**d.model_dump(), "episode": a.id} for a in analyses for d in a.decisions
    ]
    return json.dumps(items, indent=2)


def _landmines_json(analyses: list[EpisodeAnalysis]) -> str:
    items = [
        {**m.model_dump(), "episode": a.id} for a in analyses for m in a.landmines
    ]
    return json.dumps(items, indent=2)


def _index_json(manifest: dict, result: BuildResult) -> str:
    return json.dumps(
        {
            "tool": "repo-history",
            "version": __version__,
            "method": manifest.get("method"),
            "ref": manifest.get("ref"),
            "head": manifest.get("head"),
            "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "counts": {
                "episodes": result.episodes,
                "decisions": result.decisions,
                "landmines": result.landmines,
            },
        },
        indent=2,
    )


def _write(out_dir: Path, name: str, content: str, result: BuildResult) -> None:
    path = out_dir / name
    path.write_text(content if content.endswith("\n") else content + "\n")
    result.files.append(name)
